### ISSUE TITLE
AML extension install fails with "Unable to get the status from the local CRD with the error"

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#158]
Trying to install aml-extension on a newly installed k8s cluster (non-aks).
Adding cluster as arc enabled cluster works.
The arc cluster is in the same subscription and tenant as the account being used to deploy the extension.

```
az k8s-extension create --name arcml-extension --extension-type Microsoft.AzureML.Kubernetes --cluster-type connectedClusters --cluster-name NEWCLUNAME --resource-group NEWRGNAME --auto-upgrade-minor-version False --scope cluster --config enableTraining=False enableInference=True inferenceLoadBalancerHA=false allowInsecureConnections=True --debug
...
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/SUB-NAME/resourceGroups/NEWRGNAME/providers/Microsoft.Kubernetes/ConnectedClusters/NEWCLUNAME/providers/Microsoft.KubernetesConfiguration/extensions/arcml-extension/operations/8a67efee-80a4-452b-b506-60a9d17ae446?api-Version=2021-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8efbfc90-5d24-11ec-868e-1e008a0a5052'
cli.azure.cli.core.sdk.policies:     'CommandName': 'k8s-extension create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --extension-type --cluster-type --cluster-name --resource-group --auto-upgrade-minor-version --scope --config --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.31.0 (HOMEBREW) azsdk-python-mgmt-kubernetesconfiguration/1.0.0b1 Python/3.10.1 (macOS-11.6.1-x86_64-i386-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/SUB-NAME/resourceGroups/NEWRGNAME/providers/Microsoft.Kubernetes/ConnectedClusters/NEWCLUNAME/providers/Microsoft.KubernetesConfiguration/extensions/arcml-extension/operations/8a67efee-80a4-452b-b506-60a9d17ae446?api-Version=2021-09-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11983'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2019-11-01-Preview, 2021-05-01-preview, 2021-06-01-preview, 2021-09-01, 2021-11-01-preview, 2022-01-01-preview'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd324be1b-07c0-46ef-a23f-936cbe3b1407'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd324be1b-07c0-46ef-a23f-936cbe3b1407'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'FRANCECENTRAL:20211214T213430Z:d324be1b-07c0-46ef-a23f-936cbe3b1407'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 14 Dec 2021 21:34:29 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/SUB-NAME/resourceGroups/NEWRGNAME/providers/Microsoft.Kubernetes/ConnectedClusters/NEWCLUNAME/providers/Microsoft.KubernetesConfiguration/extensions/arcml-extension/operations/8a67efee-80a4-452b-b506-60a9d17ae446","name":"8a67efee-80a4-452b-b506-60a9d17ae446","status":"Failed","error":{"code":"ExtensionCreationFailed","message":" error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 483, in run
    self._poll()
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 522, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 1008, in __call__
    raise exception
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 995, in __call__
    result = poller.result()
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 501, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (ExtensionCreationFailed)  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
Code: ExtensionCreationFailed
Message:  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}

cli.azure.cli.core.azclierror: (ExtensionCreationFailed)  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
Code: ExtensionCreationFailed
Message:  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
az_command_data_logger: (ExtensionCreationFailed)  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
Code: ExtensionCreationFailed
Message:  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10e30f490>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 456.805 seconds (init: 0.093, invoke: 456.712)
```

In the "azureml" namespace, 9 pods are pending with the following errors:
```
Unable to attach or mount volumes: unmounted volumes=[tls-cert], unattached volumes=[kube-api-access-qxzgf config-volume tls-assets alertmanager-alertmanager-db ssl-certs tls-cert]: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[tls-cert], unattached volumes=[tls-assets alertmanager-alertmanager-db ssl-certs tls-cert kube-api-access-qxzgf config-volume]: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[tls-cert], unattached volumes=[tls-cert kube-api-access-qxzgf config-volume tls-assets alertmanager-alertmanager-db ssl-certs]: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[certs config kube-api-access-29w7v]: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[kube-api-access-29w7v certs config]: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[config kube-api-access-29w7v certs]: timed out waiting for the condition
MountVolume.SetUp failed for volume "certs" : secret "amlarc-identity-certs" not found
MountVolume.SetUp failed for volume "certs" : failed to sync secret cache: timed out waiting for the condition
MountVolume.SetUp failed for volume "config" : failed to sync configmap cache: timed out waiting for the condition
Unable to attach or mount volumes: unmounted volumes=[certs arc-extension-token], unattached volumes=[certs config arc-extension-token kube-api-access-m7fpd]: timed out waiting for the condition
MountVolume.SetUp failed for volume "certs" : secret "amlarc-identity-certs" not found
MountVolume.SetUp failed for volume "config" : failed to sync configmap cache: timed out waiting for the condition
MountVolume.SetUp failed for volume "certs" : failed to sync secret cache: timed out waiting for the condition
MountVolume.SetUp failed for volume "arc-extension-token" : secret "amlarc-arc-extension-token-secret" not found
...
```

Retrying yields the same result.
Didn't find any other messages
Thanks

**Comment by yuyue9284** [comment]
Hi @joaocc , could you please pin the version to 1.0.51 first by adding `--version 1.0.51`, this is a known issue for the latest release, will fix it in next release, ETA is 12/16.

**Comment by joaocc** [comment]
Worked perfectly. Thanks for the prompt response!

**Comment by kusbr** [comment]
Hi

Getting this error. Provided the version --version 1.0.51

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/71b2c773-cc3d-42a1-b58b-69d4ff85c59d/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb?api-Version=2021-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '4310a8fa-61ff-11ec-9121-cdf46ffa9fbe'
cli.azure.cli.core.sdk.policies:     'CommandName': 'k8s-extension create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --extension-type --config --cluster-type --resource-group --cluster-name --scope --auto-upgrade-minor-version --configuration-settings --version --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.1 (MSI) azsdk-python-mgmt-kubernetesconfiguration/1.0.0b1 Python/3.8.9 (Windows-10-10.0.22000-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/71b2c773-cc3d-42a1-b58b-69d4ff85c59d/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb?api-Version=2021-09-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11988'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2019-11-01-Preview, 2021-05-01-preview, 2021-06-01-preview, 2021-09-01, 2021-11-01-preview, 2022-01-01-preview'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20211221T014845Z:14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 21 Dec 2021 01:48:45 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/71b2c773-cc3d-42a1-b58b-69d4ff85c59d/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb","name":"f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb","status":"Failed","error":{"code":"ExtensionCreationFailed","message":" Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 482, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 521, in _poll
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 702, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 999, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 987, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 255, in result
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 275, in wait
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 192, in _start
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 500, in run
azure.core.exceptions.HttpResponseError: (ExtensionCreationFailed)  Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config

cli.azure.cli.core.azclierror: (ExtensionCreationFailed)  Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config
az_command_data_logger: (ExtensionCreationFailed)  Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x044540B8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 375.306 seconds (init: 0.399, invoke: 374.907)
telemetry.save: Save telemetry record of length 3547 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\kusbr\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by joaocc** [comment]
Hi
Tried reinstalling an extension without the version pinning and got that message again. I believe the version is 1.0.58. 
```
(ExtensionCreationFailed)  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
Code: ExtensionCreationFailed
Message:  error: Unable to get the status from the local CRD with the error : {Error : Retry for given duration didn't get any results with err {status not populated}}
```
Command is:
```
az k8s-extension create \
        --extension-type Microsoft.AzureML.Kubernetes \
        --cluster-type connectedClusters \
        --cluster-name NEWCLUNAME \
        --resource-group NEWRGNAME \
        --name "arcml-extension" \
        --auto-upgrade True \
                \
        --scope cluster \
        --config \
            enableTraining=True \
            enableInference=True \
            inferenceLoadBalancerHA=false \
            allowInsecureConnections=True \
            nodeSelector.agentpool=NODEPOOL_NAME_1 \
            nodeSelector.agentpool=NODEPOOL_NAME_2 \
        \
```

**Comment by joaocc** [comment]
Hi. Good some good news (version 1.0.58 works). 
It seems the `nodeSelector.agentpool` works for AKS clusters but not non-AKS cluster.
Changing this to `nodeSelector.nodepool` solved the issue.

I would say this was the cause for some of the cleanup/install jobs failing to be scheduled (as they were not finding the correct node pool) and thus being returned as error to the CLI. 

I will close the issue again.

**Comment by Bozhong68** [comment]
@joaocc thank you for the feedback, I will address the issue properly
